[Embedding]
; This section controls features related to semantic search.
; See also: https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html
; embedding_api_url default is null
embedding_api_url = "http://localhost:11434/v1/embeddings"
; embedding_api_key default is ""
embedding_api_key = ""
; embedding_site_url default is ""
embedding_site_url = ""
; embedding_app_name default is ""
embedding_app_name = ""
; vector_field default is "vector"
vector_field      = "vector"
; topK default is 10
topK              = 10
; default_core default is "biblio"
default_core      = "biblio"
; min_score default is 0.0
min_score         = 0.7
; model default is null
model             = "embeddinggemma"
; rrf_k default is 60
rrf_k             = 60
; encoding_format default is "float"
encoding_format   = "float"
; query_parser is only applied in semantic search, and is ignored in hybrid search, because hybrid search always uses "knn" for the vector search part.
; query_parser default is "knn"
; query_parser values should be "knn" or "vectorSimilarity"
; topK is ignored when query_parser is "vectorSimilarity"
query_parser      = "knn"

