<h2><?= $this->transEsc('Semantic Similar Items') ?></h2>
<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
    <ul class="list-group">
        <?php foreach ($similarRecords as $data): ?>
            <li class="list-group-item">
                <?= $this->render('Related/Similar/item.phtml', ['data' => $data]) ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><?= $this->transEsc('Cannot find similar records at this time.') ?></p>
<?php endif; ?>